interface core {
  type digest = string;

  record timestamp {
    nanos: u64
  }

  variant duration {
    secs(u64)
  }

  variant log-level {
      error,
      warn,
      info,
      debug,
      trace
  }
}
