// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package layertriggerworld represents the world "wavs:worker/layer-trigger-world@0.3.0".
package layertriggerworld

import (
	layertypes "github.com/Lay3rLabs/wavs-wasi/go/wavs/worker/layer-types"
)

// TriggerAction represents the type alias "wavs:worker/layer-trigger-world@0.3.0#trigger-action".
//
// See [layertypes.TriggerAction] for more information.
type TriggerAction = layertypes.TriggerAction
