// Code generated by wit-bindgen-go. DO NOT EDIT.

package layertriggerworld

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "wavs:worker@0.4.0-alpha.6".

//go:wasmexport run
//export run
func wasmexport_Run(triggerAction *TriggerAction) (result *cm.Result[OptionWasmResponseShape, cm.Option[WasmResponse], string]) {
	triggerAction_ := *triggerAction
	result_ := Exports.Run(triggerAction_)
	result = &result_
	return
}
