// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package layertriggerworld represents the world "wavs:worker/layer-trigger-world@0.4.0-alpha.6".
package layertriggerworld

import (
	layertypes "github.com/Lay3rLabs/wavs-wasi/go/wavs/worker/layer-types"
)

// TriggerAction represents the type alias "wavs:worker/layer-trigger-world@0.4.0-alpha.6#trigger-action".
//
// See [layertypes.TriggerAction] for more information.
type TriggerAction = layertypes.TriggerAction

// WasmResponse represents the type alias "wavs:worker/layer-trigger-world@0.4.0-alpha.6#wasm-response".
//
// See [layertypes.WasmResponse] for more information.
type WasmResponse = layertypes.WasmResponse
