[package]
name = "wavs-wasi-utils"
edition = "2021"
version = "0.3.0"
license = "MIT"
authors = ["Lay3r Labs Team"]
repository = "https://github.com/Lay3rLabs/WAVS-WASI/WAVS-WASI-utils"
rust-version = "1.84.0"

[dependencies]
wasmtime = { workspace = true }
