[package]
name = "wavs-wasi-utils"
description = "WAVS WASI utils"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
publish = true


[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
wstd = { workspace = true }
wasi = { workspace = true }
alloy-primitives = { workspace = true }
alloy-sol-types = { workspace = true }
alloy-json-rpc = { workspace = true }
alloy-provider = { workspace = true }
alloy-transport-http = { workspace = true }
alloy-transport = { workspace = true }
alloy-rpc-client = { workspace = true }
cfg-if = { workspace = true }
tower-service = { workspace = true }
futures-utils-wasm = { workspace = true }
http = { workspace = true }

[lib]
crate-type = ["rlib", "cdylib"]
